#!/usr/bin/env bash

set -eu -o pipefail

declare UPDATE=0 INTERACTIVE=1
declare VIMCMD='nvim'
declare NPM='npm'
declare PIP='pip'

readonly VIMFILES_PATH="${HOME}/.vim"

readonly GREEN='\033[0;32m'
readonly YELLOW='\033[0;33m'
readonly BOLD=$(tput bold)
readonly NORMAL=$(tput sgr0)
readonly END_COLOR='\033[0;m'

DEBUG=${DEBUG:-}
if [[ ${DEBUG} ]]; then
  set -x
fi

install_dotfiles() {
  declare script_name=$0
  local dir

  dir="$(cd "$(dirname "${script_name}")" && pwd)"
  if [[ "$(basename "${dir}")" == "bin" ]]; then
    dir="$(cd "${dir}"/.. && pwd)"
  fi

  cp "${dir}/.tmux.conf" $HOME
  cp "${dir}/.zshrc" $HOME
  cp -R "${dir}/.vim" $VIMFILES_PATH

  #XDG
  ## https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
  mkdir -p "${XDG_CONFIG_HOME:="${HOME}/.config"}"
  cp -R $dir/.config/.fish $HOME/.config/.fish
  if [[ ! -e "${XDG_CONFIG_HOME}/nvim" ]]; then
    ln -s "${VIMFILES_PATH}" "${XDG_CONFIG_HOME}/nvim"
  fi
}

setup_neovim() {
  sudo apt -y install nvim
  sudo apt -y install python3-pip
  $PIP install --upgrade neovim
}

setup_vim_calls() {
  if has_neovim; then
    VIMCMD=nvim
  fi

  exec 4>&1 3>/dev/null
  if [[ $INTERACTIVE != 1 ]] ; then
    if has_neovim; then
      VIMCMD='nvim --headless'
    else
      exec 4>&1 1>&3 2>&3
    fi
  fi
}

install_plugins() {
  echo -e "${YELLOW}INSTALL${END_COLOR} ${BOLD}vim plugins${NORMAL} (may take a while)..."

  ALL_PLUGINS='true' ${VIMCMD} +'PlugClean!' +'PlugUpdate!' +'qall!'

  ${VIMCMD} +'UpdateRemotePlugins' +'qall!'
  echo

  echo -e "${GREEN}DONE${END_COLOR} ${BOLD}vim plugins${NORMAL}" >&4
}

main() {
  # update
  git submodule update --init --recursive
  sudo apt update

  # dotfiles -> HOME
  install_dotfiles

  # essentials
  sudo apt -y install git jq curl htop silversearcher-ag
  # tmux
  sudo apt -y install tmux

  setup_neovim


  setup_vim_calls

  install_plugins

  return 0
}

main "$@"
